[package]
name = "sudoru"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[dependencies]
macroquad = "0.4.14"
rand = "0.9.2"

[build-dependencies]
static_vcruntime = "2.0.0"
